### ISSUE TITLE
Recently stopped working "This plugin is not responding."

### ISSUE THREAD

**Issue by ldwrs** [wernerkarlheisenberg/plex-vrt_nu_live#3]
This plugin worked great before but now just gives the error "This plugin is not responding.".

**Comment by wernerkarlheisenberg** [comment]
Thanks for reaching out. I'm not actively using the plugin so didn't notice myself. Plugin is also no longer working for me. I will have a look at it and report back.

**Comment by wernerkarlheisenberg** [comment]
Did some minor update. Could you retry?

**Comment by ldwrs** [comment]
Yes, that fixed it 👍 
Thanks a lot! :)
